CREATE TABLE ETL_JOB_STATUS
(
    ID                NUMBER,
	ETL_JOB_NAME      VARCHAR2(100),
	STATUS_NAME       VARCHAR2(100), 
	STATUS_TIMESTAMP  TIMESTAMP(9),
	ERROR_MESSAGE     VARCHAR2(255),
	CONSTRAINT PK_ETL_JOB_STATUS PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_ETL_JOB_STATUS
START WITH 1
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRG_BI_ETL_JOB_STATUS
BEFORE INSERT ON ETL_JOB_STATUS
 FOR EACH ROW
   BEGIN
     SELECT SEQ_ETL_JOB_STATUS.NEXTVAL INTO :NEW.ID FROM DUAL;
   END;
 
 
 
 