CREATE OR REPLACE PROCEDURE LOAD_INVOICE_FACT
(
  
  
  
  )
  
  
  AS
  
  SQLSTMT      VARCHAR2(3000);
  TBLCOUNT NUMBER :=0;
  BEGIN_AS_OF_DATE DATE;
  END_AS_OF_DATE DATE;
  ERR_MSG  VARCHAR2(200);
  
  BEGIN 

 --Log the begin of the job
 INSERT INTO ETL_JOB_STATUS( ID, ETL_JOB_NAME, STATUS_NAME, STATUS_TIMESTAMP )
 VALUES(SEQ_ETL_JOB_STATUS.NEXTVAL, 'LOAD_JOB_FACT','IN PROGRESS',SYSTIMESTAMP);
 
 COMMIT;
 
 SELECT COUNT(*) INTO TBLCOUNT FROM ALL_TABLES WHERE TABLE_NAME = 'STAGE_JOB_DATA' AND OWNER = (SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL);
 IF TBLCOUNT > 0 THEN
 EXECUTE IMMEDIATE 'DROP TABLE STAGE_JOB_DATA';
 END IF;
 
 