-- drop existing table
-- Only need to drop table if you have previously created it


DROP TABLE CUSTLOCATION;

ALTER SESSION set nls_date_format = 'yyyy-mm-dd';

-- Create table


/*********************************
        CUSTLOCATION
**********************************/


CREATE TABLE CUSTLOCATION

(
 CUST_LOC_KEY NUMBER(10,0) PRIMARY KEY,
 CUST_NAME VARCHAR2(50) NOT NULL, 
 ACTIVE CHAR(1),
 ADDRESS_1 VARCHAR2(25),
 ADDRESS_2 VARCHAR2(25),
 ADDRESS_3 VARCHAR2(25),
 CITY VARCHAR2(25) NOT NULL,
 COUNTRY VARCHAR2(25) NOT NULL,
 CREDIT_LIMIT NUMBER(10,2),
 DATE_FIRST_ORDER DATE,
 E_MAIL_ADDRESS VARCHAR2(50) NOT NULL,
 FAX VARCHAR2(10),
 PHONE VARCHAR2(10) NOT NULL,
 SALES_TAX_CODE VARCHAR2(10) NOT NULL,
 STATE VARCHAR2(2) NOT NULL,
 TERMS_CODE VARCHAR2(10) NOT NULL,
 ZIP VARCHAR2(10) NOT NULL,
 CUST_KEY NUMBER(10,0) NOT NULL,
 CONSTRAINT FK_CUSTOMER_CUSTLOCATION FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)

);