

CREATE TABLE CUSTOMER
(

  CUST_KEY NUMBER(10,0) PRIMARY KEY,
  CUST_NAME VARCHAR2(50) NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  ADDRESS_1 VARCHAR2(25),
  ADDRESS_2 VARCHAR2(25),
  ADDRESS_3 VARCHAR(25),
  CITY VARCHAR2(25) NOT NULL,
  COUNTRY VARCHAR2(25) NOT NULL,
  CREDIT_LIMIT NUMBER(10,2),
  DATE_FIRST_ORDER DATE, 
  E_MAIL_ADDRESS VARCHAR2(50) NOT NULL,
  FAX VARCHAR2(10),
  PHONE VARCHAR2(10),
  SALES_TAX_CODE VARCHAR2(10),
  STATE VARCHAR2(2) NOT NULL,
  TERMS_CODE VARCHAR2(10) NOT NULL,
  ZIP VARCHAR2(10) NOT NULL

);