REM INSERTING into MACHINETYPE
SET DEFINE OFF;
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (1,'Manufacturer A','Model 1',40,5);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (2,'Manufacturer A','Model 2',20,3);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (3,'Manufacturer B','Model 101',100,12);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (4,'Manufacturer C','Model 201',50,4);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (5,'Manufacturer C','Model 202',30,2);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (6,'Manufacturer C','Model 203',8,1);
Insert into MACHINETYPE (MACHINE_TYPE_ID,MANUFACTURER,MODEL,RATE_PER_HOUR,NUMBER_OF_MACHINES) values (7,'Manufacturer D','Model 301',60,4);