REM INSERTING into SALESCLASS
SET DEFINE OFF;
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (1,'Debit Smart',1.6);
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (2,'Credit Smart',1.6);
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (3,'Debit NoSmart',0.8);
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (4,'Credit NoSmart',0.8);
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (5,'Prepaid NoSmart',0.8);
Insert into SALESCLASS (SALES_CLASS_ID,SALES_CLASS_DESC,BASE_PRICE) values (6,'Loyalty NoSmart',0.8);