
CREATE TABLE INVOICE
(
 INVOICE_ID NUMBER(10,0) PRIMARY KEY,
 DATE_INVOICED DATE NOT NULL,
 DATE_DUE DATE NOT NULL,
 POSTING_DATE DATE NOT NULL,
 INVOICE_DESC VARCHAR2(250),
 INVOICE_AMOUNT NUMBER(10,2) NOT NULL,
 INVOICE_QUANTITY NUMBER(8,0),
 INVOICE_SHIPPED NUMBER(8,0) ,
 CUST_KEY NUMBER(10,0) NOT NULL, 
 CONSTRAINT FK_CUSTOMER_INVOICE FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)
 );