-- drop existing table
-- Only need to drop table if you have previously created it


DROP TABLE JOB;

ALTER SESSION set nls_date_format = 'yyyy-mm-dd';

-- Create table

/*********************************
             JOB
**********************************/

CREATE TABLE JOB
(
 JOB_ID NUMBER(10,0) PRIMARY KEY, 
 JOB_DESC VARCHAR2(50),
 CONTRACT_DATE DATE,
 DATE_PROMISED DATE, 
 NUMBER_OF_SUBJOBS NUMBER(4,0) NOT NULL,
 PO_NUMBER VARCHAR2(10),
 RECORD_ACTIVE CHAR(1),
 DATE_SHIP_BY DATE,
 JOB_COMPLETE CHAR(1),
 PRINT_FLOW_STATUS VARCHAR2(10),
 CONTACT_NAME VARCHAR2(50) NOT NULL,
 UNIT_PRICE NUMBER(8,4),
 QUANTITY_ORDERED NUMBER(8,0),
 QUOTATION_AMOUNT NUMBER(10,2),
 QUOTATION_ORDERED NUMBER(8,0),
 LOCATION_ID NUMBER(10,0) NOT NULL,
 SALES_CLASS_ID NUMBER(10,0) NOT NULL,
 SALES_AGENT_ID NUMBER(10,0) NOT NULL,
 CUST_KEY NUMBER(10,0) NOT NULL,
 CONSTRAINT FK_LOCATION_JOB FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
 CONSTRAINT FK_SALESCLASS_JOB FOREIGN KEY(SALES_CLASS_ID) REFERENCES SALESCLASS(SALES_CLASS_ID),
 CONSTRAINT FK_SALESAGENT_JOB FOREIGN KEY(SALES_AGENT_ID) REFERENCES SALESAGENT(SALES_AGENT_ID),
 CONSTRAINT FK_CUSTOMER_JOB FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)
);