CREATE TABLE MACHINETYPE
(
 MACHINE_TYPE_ID NUMBER(10,0) PRIMARY KEY, 
 MANUFACTURER VARCHAR2(50) NOT NULL,
 MODEL VARCHAR2(10) NOT NULL,
 RATE_PER_HOUR NUMBER(7,2) NOT NULL,
 NUMBER_OF_MACHINES NUMBER(4,0) NOT NULL
);