
CREATE TABLE SALESAGENT
(
  SALES_AGENT_ID NUMBER(10,0) PRIMARY KEY,
  SALES_AGENT_NAME VARCHAR2(60) NOT NULL,
  STATE VARCHAR2(2) NOT NULL,
  COUNTRY VARCHAR2(25) NOT NULL,
  RECORD_ACTIVE BOOLEAN NOT NULL
);