-- drop existing tables
-- Only need to drop tables if you have previously created them

DROP TABLE SHIPMENT;
DROP TABLE INVOICE;
DROP TABLE SUBJOB;
DROP TABLE JOB;
DROP TABLE MACHINETYPE
DROP TABLE LOCATION;
DROP TABLE SALESCLASS;
DROP TABLE SALESAGENT;
DROP TABLE CUSTLOCATION;
DROP TABLE CUSTOMER;

ALTER SESSION set nls_date_format = 'yyyy-mm-dd';

-- create tables

/*********************************
        CUSTOMER
**********************************/

CREATE TABLE CUSTOMER
(

  CUST_KEY NUMBER(10,0) PRIMARY KEY,
  CUST_NAME VARCHAR2(50) NOT NULL,
  ACTIVE CHAR(1) NOT NULL,
  ADDRESS_1 VARCHAR2(25),
  ADDRESS_2 VARCHAR2(25),
  ADDRESS_3 VARCHAR(25),
  CITY VARCHAR2(25) NOT NULL,
  COUNTRY VARCHAR2(25) NOT NULL,
  CREDIT_LIMIT NUMBER(10,2),
  DATE_FIRST_ORDER DATE, 
  E_MAIL_ADDRESS VARCHAR2(50) NOT NULL,
  FAX VARCHAR2(10),
  PHONE VARCHAR2(10),
  SALES_TAX_CODE VARCHAR2(10),
  STATE VARCHAR2(2) NOT NULL,
  TERMS_CODE VARCHAR2(10) NOT NULL,
  ZIP VARCHAR2(10) NOT NULL

);

/*********************************
        CUSTLOCATION
**********************************/

CREATE TABLE CUSTLOCATION

(
 CUST_LOC_KEY NUMBER(10,0) PRIMARY KEY,
 CUST_NAME VARCHAR2(50) NOT NULL, 
 ACTIVE CHAR(1),
 ADDRESS_1 VARCHAR2(25),
 ADDRESS_2 VARCHAR2(25),
 ADDRESS_3 VARCHAR2(25),
 CITY VARCHAR2(25) NOT NULL,
 COUNTRY VARCHAR2(25) NOT NULL,
 CREDIT_LIMIT NUMBER(10,2),
 DATE_FIRST_ORDER DATE,
 E_MAIL_ADDRESS VARCHAR2(50) NOT NULL,
 FAX VARCHAR2(10),
 PHONE VARCHAR2(10) NOT NULL,
 SALES_TAX_CODE VARCHAR2(10) NOT NULL,
 STATE VARCHAR2(2) NOT NULL,
 TERMS_CODE VARCHAR2(10) NOT NULL,
 ZIP VARCHAR2(10) NOT NULL,
 CUST_KEY NUMBER(10,0) NOT NULL,
 CONSTRAINT FK_CUSTOMER_CUSTLOCATION FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)

);

/*********************************
        SALESAGENT
**********************************/

CREATE TABLE SALESAGENT
(
  SALES_AGENT_ID NUMBER(10,0) PRIMARY KEY,
  SALES_AGENT_NAME VARCHAR2(60) NOT NULL,
  STATE VARCHAR2(2) NOT NULL,
  COUNTRY VARCHAR2(25) NOT NULL,
  RECORD_ACTIVE CHAR(1) NOT NULL
);

/*********************************
        SALESCLASS
**********************************/

CREATE TABLE SALESCLASS
(
 SALES_CLASS_ID NUMBER(10,0) PRIMARY KEY,
 SALES_CLASS_DESC VARCHAR2(250),
 BASE_PRICE NUMBER(8,4) NOT NULL
);

/*********************************
        LOCATION
**********************************/

CREATE TABLE LOCATION
(
 LOCATION_ID NUMBER(10,0) PRIMARY KEY,
 LOCATION_NAME VARCHAR2(50) NOT NULL
);

/*********************************
        MACHINETYPE
**********************************/

CREATE TABLE MACHINETYPE
(
 MACHINE_TYPE_ID NUMBER(10,0) PRIMARY KEY, 
 MANUFACTURER VARCHAR2(50) NOT NULL,
 MODEL VARCHAR2(10) NOT NULL,
 RATE_PER_HOUR NUMBER(7,2) NOT NULL,
 NUMBER_OF_MACHINES NUMBER(4,0) NOT NULL
);

/*********************************
             JOB
**********************************/

CREATE TABLE JOB
(
 JOB_ID NUMBER(10,0) PRIMARY KEY, 
 JOB_DESC VARCHAR2(50),
 CONTRACT_DATE DATE,
 DATE_PROMISED DATE, 
 NUMBER_OF_SUBJOBS NUMBER(4,0) NOT NULL,
 PO_NUMBER VARCHAR2(10),
 RECORD_ACTIVE CHAR(1),
 DATE_SHIP_BY DATE,
 JOB_COMPLETE CHAR(1),
 PRINT_FLOW_STATUS VARCHAR2(10),
 CONTACT_NAME VARCHAR2(50) NOT NULL,
 UNIT_PRICE NUMBER(8,4),
 QUANTITY_ORDERED NUMBER(8,0),
 QUOTATION_AMOUNT NUMBER(10,2),
 QUOTATION_ORDERED NUMBER(8,0),
 LOCATION_ID NUMBER(10,0) NOT NULL,
 SALES_CLASS_ID NUMBER(10,0) NOT NULL,
 SALES_AGENT_ID NUMBER(10,0) NOT NULL,
 CUST_KEY NUMBER(10,0) NOT NULL,
 CONSTRAINT FK_LOCATION_JOB FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
 CONSTRAINT FK_SALESCLASS_JOB FOREIGN KEY(SALES_CLASS_ID) REFERENCES SALESCLASS(SALES_CLASS_ID),
 CONSTRAINT FK_SALESAGENT_JOB FOREIGN KEY(SALES_AGENT_ID) REFERENCES SALESAGENT(SALES_AGENT_ID),
 CONSTRAINT FK_CUSTOMER_JOB FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)
);

/*********************************
        SUBJOB
**********************************/

CREATE TABLE SUBJOB
(
 SUB_JOB_ID NUMBER(10,0),
 JOB_ID NUMBER(10,0),
 SUB_JOB_DESC VARCHAR2(50),
 COST_LABOR NUMBER(8,2) NOT NULL,
 COST_MATERIAL NUMBER(8,2) NOT NULL,
 COST_OVERHEAD NUMBER(8,2) NOT NULL,
 MACHINE_HOURS NUMBER(8,2) NOT NULL,
 DATE_PROD_BEGIN DATE NOT NULL, 
 DATE_PROD_END DATE NOT NULL, 
 QUANTITY_PRODUCED NUMBER(8,0) NOT NULL, 
 SUB_JOB_AMOUNT NUMBER(11,2) NOT NULL,
 MACHINE_TYPE_ID NUMBER(10,0) NOT NULL,
 CONSTRAINT PK_SUBJOB PRIMARY KEY(SUB_JOB_ID, JOB_ID),
 CONSTRAINT FK_MACHINETYPE_SUBJOB FOREIGN KEY(MACHINE_TYPE_ID) REFERENCES MACHINETYPE(MACHINE_TYPE_ID),
 CONSTRAINT FK_JOB_SUBJOB FOREIGN KEY(JOB_ID) REFERENCES JOB(JOB_ID)
);

/*********************************
        INVOICE
**********************************/

CREATE TABLE INVOICE
(
 INVOICE_ID NUMBER(10,0) PRIMARY KEY,
 DATE_INVOICED DATE NOT NULL,
 DATE_DUE DATE NOT NULL,
 POSTING_DATE DATE NOT NULL,
 INVOICE_DESC VARCHAR2(250),
 INVOICE_AMOUNT NUMBER(10,2) NOT NULL,
 INVOICE_QUANTITY NUMBER(8,0),
 INVOICE_SHIPPED NUMBER(8,0) ,
 CUST_KEY NUMBER(10,0) NOT NULL, 
 CONSTRAINT FK_CUSTOMER_INVOICE FOREIGN KEY(CUST_KEY) REFERENCES CUSTOMER(CUST_KEY)
 );

/*********************************
        SHIPMENT
**********************************/

CREATE TABLE SHIPMENT
(
  SHIPMENT_ID NUMBER(10,0) PRIMARY KEY,
  ACTUAL_SHIP_DATE DATE NOT NULL,
  REQUESTED_SHIP_DATE DATE NOT NULL, 
  ACTUAL_QUANTITY NUMBER(8,0) NOT NULL, 
  REQUESTED_QUANTITY NUMBER(8,0) NOT NULL,
  BOXES NUMBER(4,0) NOT NULL,
  QUANTITY_PER_BOX NUMBER(5,0) NOT NULL,
  QUANTITY_PER_PARTIAL_BOX NUMBER(5,0) NOT NULL,
  JOB_ID NUMBER(10,0),
  SHIPMENT_AMOUNT NUMBER(8,2) NOT NULL,
  SUB_JOB_ID NUMBER(10,0) NOT NULL,
  INVOICE_ID NUMBER(10,0) NOT NULL,
  CUST_LOC_KEY NUMBER(10,0) NOT NULL,
  CONSTRAINT FK_SUBJOB_SHIPMENT FOREIGN KEY(SUB_JOB_ID, JOB_ID) REFERENCES SUBJOB(SUB_JOB_ID,JOB_ID),
  CONSTRAINT FK_INVOICE_SHIPMENT FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
  CONSTRAINT FK_CUSTLOCATION_SHIPMENT FOREIGN KEY(CUST_LOC_KEY) REFERENCES CUSTLOCATION(CUST_LOC_KEY)
);


 


