/*********************************
        SUBJOB
**********************************/

CREATE TABLE SUBJOB
(
 JOB_ID NUMBER(10,0),
 SUB_JOB_ID NUMBER(10,0) PRIMARY KEY,
 SUB_JOB_DESC VARCHAR2(50),
 COST_LABOR NUMBER(8,2) NOT NULL,
 COST_MATERIAL NUMBER(8,2) NOT NULL,
 COST_OVERHEAD NUMBER(8,2) NOT NULL,
 MACHINE_HOURS NUMBER(8,2) NOT NULL,
 DATE_PROD_BEGIN DATE NOT NULL, 
 DATE_PROD_END DATE NOT NULL, 
 QUANTITY_PRODUCED NUMBER(8,0) NOT NULL, 
 SUB_JOB_AMOUNT NUMBER(11,2) NOT NULL,
 MACHINE_TYPE_ID NUMBER(10,0) NOT NULL,
 CONSTRAINT FK_MACHINETYPE_SUBJOB FOREIGN KEY(MACHINE_TYPE_ID) REFERENCES MACHINETYPE(MACHINE_TYPE_ID),
 CONSTRAINT FK_JOB_SUBJOB FOREIGN KEY(JOB_ID) REFERENCES JOB(JOB_ID)
);