-- drop existing tables
-- Only need to drop tables if you have previously created them


DROP TABLE W_JOB_F;
DROP TABLE W_LOCATION_D;
DROP TABLE W_TIME_D;
DROP TABLE W_SALES_CLASS_D;
DROP TABLE W_SALES_AGENT_D;
DROP TABLE W_CUSTOMER_D;

-- create tables

/*********************************
        W_CUSTOMER_D
**********************************/

  CREATE TABLE W_CUSTOMER_D
   (	CUST_KEY 	NUMBER(8,0) 		NOT NULL , 
	CUST_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CITY 		VARCHAR2(25 BYTE) 	NOT NULL , 
	COUNTRY 	VARCHAR2(25 BYTE) 	NOT NULL , 
	CREDIT_LIMIT 	NUMBER(10,2), 
	E_MAIL_ADDRESS 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CUST_STATE 	VARCHAR2(2 BYTE) 	NOT NULL , 
	ZIP 		VARCHAR2(10 BYTE) 	NOT NULL , 
	TERMS_CODE 	VARCHAR2(10 BYTE) 	NOT NULL , 
	 CHECK ( REGEXP_LIKE(e_mail_address, '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}')) , 
	 CONSTRAINT W_CUSTOMER_D_PK PRIMARY KEY (CUST_KEY)
 );
 
 /*********************************
        W_SALES_AGENT_D
**********************************/   

  CREATE TABLE W_SALES_AGENT_D 
   (	SALES_AGENT_ID 		NUMBER(10,0) 		NOT NULL , 
	SALES_AGENT_NAME 	VARCHAR2(60 BYTE) 	NOT NULL , 
	SALES_AGENT_STATE 	VARCHAR2(2 BYTE) 	NOT NULL , 
	COUNTRY 		VARCHAR2(25 BYTE) 	NOT NULL ENABLE, 
  
  CONSTRAINT W_SALES_AGENT_D_PK PRIMARY KEY (SALES_AGENT_ID)
  );
  
  /*********************************
        W_SALES_CLASS_D
**********************************/

  CREATE TABLE W_SALES_CLASS_D 
   (	SALES_CLASS_ID 		NUMBER(10,0) 		NOT NULL , 
	SALES_CLASS_DESC 	VARCHAR2(250 BYTE), 
	BASE_PRICE 		NUMBER(8,4) 		NOT NULL , 
  
	 CONSTRAINT W_SALES_CLASS_D_PK PRIMARY KEY (SALES_CLASS_ID)
  );
  
/*********************************
        W_TIME_D
**********************************/   

  CREATE TABLE W_TIME_D 
   (	TIME_ID 	NUMBER(8,0) 	NOT NULL , 
	TIME_YEAR 	NUMBER(4,0) 	NOT NULL , 
	TIME_QUARTER 	NUMBER(1,0) 	NOT NULL , 
	TIME_MONTH 	NUMBER(2,0) 	NOT NULL , 
	TIME_DAY 	NUMBER(3,0) 	NOT NULL , 
	TIME_WEEK 	NUMBER(2,0) 	NOT NULL , 
  
  CONSTRAINT W_TIME_D_PK PRIMARY KEY (TIME_ID) ,
  CONSTRAINT W_TIME_D_UNIQUEGOUP1 UNIQUE (TIME_YEAR, TIME_MONTH, TIME_DAY)
  
 );
 
 /*********************************
        W_LOCATION_D
**********************************/  

  CREATE TABLE W_LOCATION_D 
   (	LOCATION_ID 	NUMBER(10,0) 		NOT NULL , 
	LOCATION_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
  
	 CONSTRAINT W_LOCATION_PK PRIMARY KEY (LOCATION_ID) ,
 	 CONSTRAINT W_LOCATION_UNIQUE1 UNIQUE (LOCATION_NAME)
  );
  
  /*********************************
        W_JOB_F
**********************************/    

    CREATE TABLE W_JOB_F 
   (	JOB_ID 			NUMBER(10,0) 	NOT NULL , 
	CONTRACT_DATE 		NUMBER(10,0), 
	SALES_AGENT_ID 		NUMBER(10,0) 	NOT NULL , 
	SALES_CLASS_ID 		NUMBER(10,0), 
	LOCATION_ID 		NUMBER(10,0) 	NOT NULL , 
	CUST_ID_ORDERED_BY 	NUMBER(10,0) 	NOT NULL , 
	DATE_PROMISED 		NUMBER(10,0), 
	DATE_SHIP_BY 		NUMBER(10,0), 
	NUMBER_OF_SUBJOBS 	NUMBER(4,0) 	NOT NULL , 
	UNIT_PRICE 		NUMBER(6,2) 	NOT NULL , 
	QUANTITY_ORDERED 	NUMBER(8,0) 	NOT NULL , 
	QUOTE_QTY 		NUMBER(8,0) 	NOT NULL , 
  
  CONSTRAINT W_JOB_F_PK PRIMARY KEY (JOB_ID) , 
  CONSTRAINT W_JOB_CONTRACT_DATE_FK FOREIGN KEY (CONTRACT_DATE)	  REFERENCES W_TIME_D (TIME_ID) , 
	 CONSTRAINT W_JOB_SALES_AGENT_ID_FK FOREIGN KEY (SALES_AGENT_ID)   REFERENCES W_SALES_AGENT_D (SALES_AGENT_ID)  , 
	 CONSTRAINT W_JOB_SALES_CLASS_ID_FK FOREIGN KEY (SALES_CLASS_ID) 	  REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID) , 
	 CONSTRAINT W_JOB_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) 	 REFERENCES W_LOCATION_D (LOCATION_ID)  , 
	 CONSTRAINT W_JOB_CUST_ID_ORDERED_BY_FK FOREIGN KEY (CUST_ID_ORDERED_BY) REFERENCES W_CUSTOMER_D (CUST_KEY) , 
	 CONSTRAINT W_JOB_DATE_PROMISED_FK FOREIGN KEY (DATE_PROMISED) REFERENCES W_TIME_D (TIME_ID)  , 
	 CONSTRAINT W_JOB_DATE_SHIP_BY_FK FOREIGN KEY (DATE_SHIP_BY) REFERENCES W_TIME_D (TIME_ID)  
   );
   
   
