-- drop existing tables
-- Only need to drop tables if you have previously created them

DROP TABLE W_JOB_SHIPMENT_F;
DROP TABLE W_LOCATION_D;
DROP TABLE W_TIME_D;
DROP TABLE W_SALES_CLASS_D;
DROP TABLE W_CUST_LOCATION_D;
DROP TABLE W_CUSTOMER_D;

-- create tables

/*********************************
        W_CUSTOMER_D
**********************************/

  CREATE TABLE W_CUSTOMER_D
   (	CUST_KEY 	NUMBER(8,0) 		NOT NULL , 
	CUST_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CITY 		VARCHAR2(25 BYTE) 	NOT NULL , 
	COUNTRY 	VARCHAR2(25 BYTE) 	NOT NULL , 
	CREDIT_LIMIT 	NUMBER(10,2), 
	E_MAIL_ADDRESS 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CUST_STATE 	VARCHAR2(2 BYTE) 	NOT NULL , 
	ZIP 		VARCHAR2(10 BYTE) 	NOT NULL , 
	TERMS_CODE 	VARCHAR2(10 BYTE) 	NOT NULL , 
	 CHECK ( REGEXP_LIKE(e_mail_address, '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}')) , 
	 CONSTRAINT W_CUSTOMER_D_PK PRIMARY KEY (CUST_KEY)
 );
 
 
/*********************************
        W_CUST_LOCATION_D
**********************************/

  CREATE TABLE W_CUST_LOCATION_D 
   (	
   
  CUST_LOC_KEY NUMBER(10,0) NOT NULL , 
	CITY VARCHAR2(25 BYTE) NOT NULL , 
	COUNTRY VARCHAR2(25 BYTE) NOT NULL , 
	CREDIT_LIMIT NUMBER(10,2) NOT NULL , 
	E_MAIL_ADDRESS VARCHAR2(50 BYTE) NOT NULL , 
	CUST_LOCATION_STATE VARCHAR2(2 BYTE) NOT NULL , 
	ZIP VARCHAR2(10 BYTE) NOT NULL , 
	CUST_KEY NUMBER(10,0) NOT NULL , 
	CUST_NAME VARCHAR2(50 BYTE) NOT NULL , 
  
  CONSTRAINT W_CUST_LOCATION_D_PK PRIMARY KEY (CUST_LOC_KEY) ,
  CONSTRAINT CUST_NAME_UNIQUE UNIQUE (CUST_NAME) ,
  CONSTRAINT CUST_KEY_FK FOREIGN KEY (CUST_KEY)  REFERENCES W_CUSTOMER_D (CUST_KEY) ON DELETE CASCADE  
   );
   
/*********************************
        W_SALES_CLASS_D
**********************************/

  CREATE TABLE W_SALES_CLASS_D 
   (	SALES_CLASS_ID 		NUMBER(10,0) 		NOT NULL , 
	SALES_CLASS_DESC 	VARCHAR2(250 BYTE), 
	BASE_PRICE 		NUMBER(8,4) 		NOT NULL , 
  
	 CONSTRAINT W_SALES_CLASS_D_PK PRIMARY KEY (SALES_CLASS_ID)
  );
  
/*********************************
        W_TIME_D
**********************************/   

  CREATE TABLE W_TIME_D 
   (	TIME_ID 	NUMBER(8,0) 	NOT NULL , 
	TIME_YEAR 	NUMBER(4,0) 	NOT NULL , 
	TIME_QUARTER 	NUMBER(1,0) 	NOT NULL , 
	TIME_MONTH 	NUMBER(2,0) 	NOT NULL , 
	TIME_DAY 	NUMBER(3,0) 	NOT NULL , 
	TIME_WEEK 	NUMBER(2,0) 	NOT NULL , 
  
  CONSTRAINT W_TIME_D_PK PRIMARY KEY (TIME_ID) ,
  CONSTRAINT W_TIME_D_UNIQUEGOUP1 UNIQUE (TIME_YEAR, TIME_MONTH, TIME_DAY)
  
 );

/*********************************
        W_LOCATION_D
**********************************/  

  CREATE TABLE W_LOCATION_D 
   (	LOCATION_ID 	NUMBER(10,0) 		NOT NULL , 
	LOCATION_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
  
	 CONSTRAINT W_LOCATION_PK PRIMARY KEY (LOCATION_ID) ,
 	 CONSTRAINT W_LOCATION_UNIQUE1 UNIQUE (LOCATION_NAME)
  );

/*********************************
        W_JOB_SHIPMENT_F
**********************************/   

  CREATE TABLE W_JOB_SHIPMENT_F 
   (	
   
  JOB_SHIPMENT_ID NUMBER(10,0) NOT NULL , 
	ACTUAL_QUANTITY NUMBER(8,0) NOT NULL , 
	REQUESTED_QUANTITY NUMBER(8,0) NOT NULL , 
	BOXES NUMBER(4,0) NOT NULL , 
	QUANTITY_PER_BOX NUMBER(5,0) NOT NULL , 
	QUANTITY_PER_PARTIAL_BOX NUMBER(4,0), 
	SHIPPED_AMOUNT NUMBER(8,2) NOT NULL , 
	SUB_JOB_ID NUMBER(10,0) NOT NULL , 
	SALES_CLASS_ID NUMBER(10,0) NOT NULL , 
	LOCATION_ID NUMBER(10,0) NOT NULL , 
	CUST_ID_SHIP_TO NUMBER(10,0) NOT NULL , 
	ACTUAL_SHIP_DATE NUMBER(10,0) NOT NULL , 
	REQUESTED_SHIP_DATE NUMBER(10,0) NOT NULL , 
	INVOICE_ID NUMBER(10,0), 
  
  CONSTRAINT W_JOB_SHIPMENT_F_PK PRIMARY KEY (JOB_SHIPMENT_ID), 
	 CONSTRAINT SHIPMENT_SALES_CLASS_ID_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID) , 
	 CONSTRAINT SHIPMENT_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID) , 
	 CONSTRAINT SHIPMENT_CUST_ID_SHIP_TO_FK FOREIGN KEY (CUST_ID_SHIP_TO) REFERENCES W_CUST_LOCATION_D (CUST_LOC_KEY) , 
	 CONSTRAINT SHIPMENT_ACTUAL_SHIP_DATE_FK FOREIGN KEY (ACTUAL_SHIP_DATE) REFERENCES W_TIME_D (TIME_ID) , 
	 CONSTRAINT SHIPMENT_REQUESTED_SHIP_DATEFK FOREIGN KEY (REQUESTED_SHIP_DATE) REFERENCES W_TIME_D (TIME_ID) 
   )  ;
