-- drop existing tables
-- Only need to drop tables if you have previously created them

DROP TABLE W_SUB_JOB_F;
DROP TABLE W_MACHINE_TYPE_D;
DROP TABLE W_LOCATION_D;
DROP TABLE W_TIME_D;
DROP TABLE W_SALES_CLASS_D;
DROP TABLE W_CUSTOMER_D;

-- create tables

/*********************************
        W_CUSTOMER_D
**********************************/

  CREATE TABLE W_CUSTOMER_D
   (	CUST_KEY 	NUMBER(8,0) 		NOT NULL , 
	CUST_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CITY 		VARCHAR2(25 BYTE) 	NOT NULL , 
	COUNTRY 	VARCHAR2(25 BYTE) 	NOT NULL , 
	CREDIT_LIMIT 	NUMBER(10,2), 
	E_MAIL_ADDRESS 	VARCHAR2(50 BYTE) 	NOT NULL , 
	CUST_STATE 	VARCHAR2(2 BYTE) 	NOT NULL , 
	ZIP 		VARCHAR2(10 BYTE) 	NOT NULL , 
	TERMS_CODE 	VARCHAR2(10 BYTE) 	NOT NULL , 
	 CHECK ( REGEXP_LIKE(e_mail_address, '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}')) , 
	 CONSTRAINT W_CUSTOMER_D_PK PRIMARY KEY (CUST_KEY)
 );
 
 /*********************************
        W_SALES_CLASS_D
**********************************/

  CREATE TABLE W_SALES_CLASS_D 
   (	SALES_CLASS_ID 		NUMBER(10,0) 		NOT NULL , 
	SALES_CLASS_DESC 	VARCHAR2(250 BYTE), 
	BASE_PRICE 		NUMBER(8,4) 		NOT NULL , 
  
	 CONSTRAINT W_SALES_CLASS_D_PK PRIMARY KEY (SALES_CLASS_ID)
  );
  
/*********************************
        W_TIME_D
**********************************/   

  CREATE TABLE W_TIME_D 
   (	TIME_ID 	NUMBER(8,0) 	NOT NULL , 
	TIME_YEAR 	NUMBER(4,0) 	NOT NULL , 
	TIME_QUARTER 	NUMBER(1,0) 	NOT NULL , 
	TIME_MONTH 	NUMBER(2,0) 	NOT NULL , 
	TIME_DAY 	NUMBER(3,0) 	NOT NULL , 
	TIME_WEEK 	NUMBER(2,0) 	NOT NULL , 
  
  CONSTRAINT W_TIME_D_PK PRIMARY KEY (TIME_ID) ,
  CONSTRAINT W_TIME_D_UNIQUEGOUP1 UNIQUE (TIME_YEAR, TIME_MONTH, TIME_DAY)
  
 );

/*********************************
        W_LOCATION_D
**********************************/  

  CREATE TABLE W_LOCATION_D 
   (	LOCATION_ID 	NUMBER(10,0) 		NOT NULL , 
	LOCATION_NAME 	VARCHAR2(50 BYTE) 	NOT NULL , 
  
	 CONSTRAINT W_LOCATION_PK PRIMARY KEY (LOCATION_ID) ,
 	 CONSTRAINT W_LOCATION_UNIQUE1 UNIQUE (LOCATION_NAME)
  );
  
/*********************************
        W_MACHINE_TYPE_D
**********************************/  

  CREATE TABLE W_MACHINE_TYPE_D 
   (	
   
  MACHINE_TYPE_ID NUMBER(10,0) NOT NULL , 
	MANUFACTURER VARCHAR2(50 BYTE) NOT NULL , 
	MACHINE_MODEL VARCHAR2(10 BYTE) NOT NULL , 
	RATE_PER_HOUR NUMBER(7,2) NOT NULL , 
	NUMBER_OF_MACHINES NUMBER(4,0) NOT NULL , 
  
	CONSTRAINT W_MACHINE_TYPE_D_PK PRIMARY KEY (MACHINE_TYPE_ID)
  
  );

/*********************************
        W_SUB_JOB_F
**********************************/  

  CREATE TABLE W_SUB_JOB_F 
   (	
   
  SUB_JOB_ID NUMBER(10,0) NOT NULL , 
	COST_LABOR NUMBER(8,2) NOT NULL , 
	COST_MATERIAL NUMBER(8,2) NOT NULL , 
	COST_OVERHEAD NUMBER(8,2) NOT NULL , 
	MACHINE_HOURS NUMBER(8,2) NOT NULL , 
	QUANTITY_PRODUCED NUMBER(8,0) NOT NULL , 
	SUB_JOB_AMOUNT NUMBER(11,2) NOT NULL , 
	JOB_ID NUMBER(10,0) NOT NULL , 
	MACHINE_TYPE_ID NUMBER(10,0) NOT NULL , 
	SALES_CLASS_ID NUMBER(10,0) NOT NULL , 
	DATE_PROD_BEGIN NUMBER(10,0) NOT NULL , 
	DATE_PROD_END NUMBER(10,0) NOT NULL , 
	LOCATION_ID NUMBER(10,0) NOT NULL , 
	CUST_ID_ORDERED_BY NUMBER(10,0) NOT NULL , 
  
  CONSTRAINT W_SUB_JOB_F_PK PRIMARY KEY (SUB_JOB_ID), 
	 CONSTRAINT SUBJOB_MACHINE_TYPE_ID FOREIGN KEY (MACHINE_TYPE_ID) REFERENCES W_MACHINE_TYPE_D (MACHINE_TYPE_ID) , 
	 CONSTRAINT SUBJOB_SALES_CLASS_ID FOREIGN KEY (SALES_CLASS_ID)  REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID) , 
	 CONSTRAINT SUBJOB_DATE_PROD_BEGIN FOREIGN KEY (DATE_PROD_BEGIN) REFERENCES W_TIME_D (TIME_ID) , 
	 CONSTRAINT SUBJOB_DATE_PROD_END FOREIGN KEY (DATE_PROD_END) REFERENCES W_TIME_D (TIME_ID) , 
	 CONSTRAINT SUBJOB_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID) , 
	 CONSTRAINT SUBJOB_CUST_ID_ORDERED_BY FOREIGN KEY (CUST_ID_ORDERED_BY)  REFERENCES W_CUSTOMER_D (CUST_KEY) 
   ) ;
   
   